# Generated by Django 5.1.4 on 2026-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Учётная запись заведена с временным паролем. Пока флаг стоит, API отдаёт 403 на всё, кроме профиля и смены пароля.",
                verbose_name="Требуется сменить пароль",
            ),
        ),
    ]
