# Generated by Django 5.1.4 on 2026-09-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("debt", "Ведомость задолженностей"),
                            ("members", "Реестр членов"),
                            ("receipts", "Поступления за период"),
                            ("reconciliation", "Акт сверки"),
                            ("annual", "Годовой финансовый отчёт"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("file", models.FileField(upload_to="reports/", verbose_name="Файл")),
                (
                    "sent_to",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Отправлен на"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлен"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="billing.billingperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт",
                "verbose_name_plural": "Отчёты",
                "ordering": ["-created_at"],
            },
        ),
    ]
