# Generated by Django 5.1.4 on 2026-09-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Месяц/квартал"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыт"), ("closed", "Закрыт")],
                        default="open",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчётный период",
                "verbose_name_plural": "Расчётные периоды",
                "ordering": ["-year", "-month"],
                "unique_together": {("organization", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ChargeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("membership", "Членский взнос"),
                            ("target", "Целевой взнос"),
                            ("electricity", "Электроэнергия"),
                            ("water", "Водоснабжение"),
                            ("garbage", "Вывоз мусора"),
                            ("security", "Охрана"),
                            ("other", "Прочее"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид начисления",
                "verbose_name_plural": "Виды начислений",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="кВт·ч",
                    ),
                ),
                (
                    "tariff",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Тариф (руб./кВт)",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="billing.billingperiod",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="members.plot",
                    ),
                ),
                (
                    "charge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="billing.chargetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление",
                "verbose_name_plural": "Начисления",
                "ordering": ["-period__year", "-period__month", "plot__number"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Дата оплаты")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("bank", "Банковский перевод"),
                            ("sbp", "СБП"),
                            ("card", "Карта"),
                            ("other", "Прочее"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Внешний ID транзакции"
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Отменён"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.charge",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-date"],
            },
        ),
    ]
