# Generated by Django 5.1.4 on 2026-09-22 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("members", "0001_initial"),
        (
            "organizations",
            "0002_organization_bank_account_organization_bank_bic_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255, verbose_name="Файл")),
                (
                    "account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Расчётный счёт"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="Период с"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="Период по"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("parsed", "Разобрана"), ("applied", "Проведена")],
                        default="parsed",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Проведена"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковская выписка",
                "verbose_name_plural": "Банковские выписки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер документа"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Плательщик"
                    ),
                ),
                (
                    "payer_account",
                    models.CharField(
                        blank=True, max_length=34, verbose_name="Счёт плательщика"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, verbose_name="Назначение платежа"),
                ),
                (
                    "match_kind",
                    models.CharField(
                        choices=[
                            ("plot", "По номеру участка"),
                            ("name", "По ФИО плательщика"),
                            ("none", "Не опознан"),
                            ("manual", "Указан вручную"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Как опознан",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Ожидает проведения"),
                            ("applied", "Проведён"),
                            ("skipped", "Пропущен"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="members.member",
                        verbose_name="Член СНТ",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="members.plot",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="billing.bankstatement",
                        verbose_name="Выписка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка выписки",
                "verbose_name_plural": "Строки выписки",
                "ordering": ["date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "date",
                            "amount",
                            "doc_number",
                            "payer_account",
                        ),
                        name="unique_bank_transaction",
                    )
                ],
            },
        ),
    ]
