# Generated by Django 5.1.4 on 2026-09-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_bankstatement_banktransaction"),
        ("members", "0001_initial"),
        (
            "organizations",
            "0002_organization_bank_account_organization_bank_bic_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Положительная — аванс зачислен, отрицательная — израсходован.",
                        max_digits=12,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_entries",
                        to="billing.charge",
                        verbose_name="Начисление",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_entries",
                        to="billing.payment",
                        verbose_name="Платёж",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="members.plot",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credits",
                        to="billing.banktransaction",
                        verbose_name="Строка выписки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение аванса",
                "verbose_name_plural": "Авансы",
                "ordering": ["-date", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["organization", "plot"],
                        name="billing_plo_organiz_2b60e5_idx",
                    )
                ],
            },
        ),
    ]
