# Generated by Django 5.1.4 on 2026-09-22 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_plotcredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotcredit",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credits",
                to="billing.billingperiod",
                verbose_name="Расчётный период",
            ),
        ),
        migrations.AddField(
            model_name="plotcredit",
            name="source",
            field=models.CharField(
                choices=[
                    ("statement", "Переплата по выписке"),
                    ("electricity", "Возврат за свет"),
                    ("manual", "Вручную"),
                ],
                default="statement",
                help_text="Нужен, чтобы повторный расчёт не выписал второй такой же возврат и при этом не затёр переплату по выписке за ту же дату.",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
