# Generated by Django 5.1.4 on 2026-09-30 05:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_plotcredit_period_plotcredit_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Оплатить до"),
        ),
        migrations.AddField(
            model_name="charge",
            name="penalty_for",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penalty",
                to="billing.charge",
                verbose_name="Пени по начислению",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="penalty_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Начисляются однократно, если к указанной дате осталась задолженность",
                max_digits=5,
                verbose_name="Пени за просрочку, %",
            ),
        ),
        migrations.AlterField(
            model_name="chargetype",
            name="category",
            field=models.CharField(
                choices=[
                    ("membership", "Членский взнос"),
                    ("target", "Целевой взнос"),
                    ("electricity", "Электроэнергия"),
                    ("water", "Водоснабжение"),
                    ("garbage", "Вывоз мусора"),
                    ("security", "Охрана"),
                    ("penalty", "Пени за просрочку"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
