# Generated by Django 5.1.4 on 2026-09-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_charge_due_date_charge_penalty_for_and_more"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personal_charges",
                to="members.member",
                verbose_name="Член товарищества",
            ),
        ),
    ]
