# Generated by Django 5.1.4 on 2026-10-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_charge_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("membership", "Членский взнос"),
                    ("target", "Целевой взнос"),
                    ("electricity", "Электроэнергия"),
                ],
                max_length=20,
                verbose_name="Назначение по категории",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("bank", "Банковский перевод"),
                    ("sbp", "СБП"),
                    ("card", "Карта"),
                    ("transfer", "Перенос между начислениями"),
                    ("other", "Прочее"),
                ],
                default="cash",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
