# Generated by Django 5.1.4 on 2026-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_banktransaction_category_alter_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="allocation",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Разнесение по категориям"
            ),
        ),
    ]
