# Generated by Django 5.1.4 on 2026-10-01 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_backfill_transaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bank_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.banktransaction",
                verbose_name="Строка выписки",
            ),
        ),
        migrations.AddField(
            model_name="plotcredit",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("membership", "Членский взнос"),
                    ("target", "Целевой взнос"),
                    ("electricity", "Электроэнергия"),
                ],
                max_length=20,
                verbose_name="Назначение аванса",
            ),
        ),
    ]
