# Generated by Django 5.1.4 on 2026-10-06 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_payment_bank_transaction_plotcredit_category"),
        ("members", "0001_initial"),
        (
            "organizations",
            "0002_organization_bank_account_organization_bank_bic_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("bank", "Банковский перевод"),
                            ("sbp", "СБП"),
                            ("card", "Карта"),
                            ("transfer", "Перенос между начислениями"),
                            ("other", "Прочее"),
                        ],
                        max_length=10,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Примечание"
                    ),
                ),
                (
                    "allocation",
                    models.TextField(blank=True, verbose_name="Куда разнесено"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="members.plot",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Принял",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поступление (касса)",
                "verbose_name_plural": "Поступления (касса)",
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
