# Generated by Django 5.1.4 on 2026-09-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Название СНТ")),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=13, verbose_name="ОГРН"),
                ),
                (
                    "legal_address",
                    models.TextField(blank=True, verbose_name="Юридический адрес"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Irkutsk",
                        max_length=50,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "fee_period",
                    models.CharField(
                        choices=[
                            ("yearly", "Ежегодно"),
                            ("quarterly", "Ежеквартально"),
                        ],
                        default="yearly",
                        max_length=10,
                        verbose_name="Периодичность взносов",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Организация (СНТ)",
                "verbose_name_plural": "Организации (СНТ)",
                "ordering": ["name"],
            },
        ),
    ]
