# Generated by Django 5.1.4 on 2026-09-22 02:44

import organizations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bank_account",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[organizations.validators.validate_account_number],
                verbose_name="Расчётный счёт",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_bic",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[organizations.validators.validate_bic],
                verbose_name="БИК",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_corr_account",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[organizations.validators.validate_account_number],
                verbose_name="Корреспондентский счёт",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Банк"),
        ),
        migrations.AddField(
            model_name="organization",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text='Как в реквизитах счёта, например: ТОВАРИЩЕСТВО СОБСТВЕННИКОВ НЕДВИЖИМОСТИ "ЗДОРОВЬЕ"',
                max_length=500,
                verbose_name="Полное наименование (для платёжных документов)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="kpp",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[organizations.validators.validate_kpp],
                verbose_name="КПП",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="inn",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[organizations.validators.validate_inn],
                verbose_name="ИНН",
            ),
        ),
    ]
