# Generated by Django 5.1.4 on 2026-09-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Как показывать в интерфейсе, например «ЮKassa — взносы».",
                        max_length=120,
                        verbose_name="Название",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("yookassa", "ЮKassa"),
                            ("tbank", "Т-Банк Эквайринг"),
                            ("sbp", "СБП напрямую через банк"),
                            ("manual", "Вручную (без онлайн-оплаты)"),
                        ],
                        max_length=20,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("in", "Приём взносов от членов"),
                            ("out", "Обязательные платежи товарищества"),
                        ],
                        default="in",
                        help_text="Приём денег от членов или оплата налогов и обязательных платежей.",
                        max_length=3,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        blank=True,
                        help_text="shopId у ЮKassa, TerminalKey у Т-Банка.",
                        max_length=120,
                        verbose_name="Идентификатор мерчанта",
                    ),
                ),
                (
                    "secret_encrypted",
                    models.TextField(
                        blank=True, verbose_name="Секретный ключ (шифрованный)"
                    ),
                ),
                (
                    "test_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Платежи не настоящие. Снимать только после проверки приёма денег.",
                        verbose_name="Тестовый режим",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Используется по умолчанию для своего направления.",
                        verbose_name="Основной",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёжный провайдер",
                "verbose_name_plural": "Платёжные провайдеры",
                "ordering": ["organization", "direction", "-is_default", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("organization", "direction"),
                        name="unique_default_provider_per_direction",
                    )
                ],
            },
        ),
    ]
