# Generated by Django 5.1.4 on 2026-09-14 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Оплачено"),
                            ("canceled", "Отменено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                (
                    "confirmation_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Ссылка на оплату"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оплачено"
                    ),
                ),
                (
                    "last_event",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Последнее событие провайдера",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Причина ошибки"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="members.member",
                        verbose_name="Плательщик",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intents",
                        to="payments.paymentprovider",
                        verbose_name="Провайдер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Намерение оплаты",
                "verbose_name_plural": "Намерения оплаты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentIntentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intent_items",
                        to="billing.charge",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка намерения оплаты",
                "verbose_name_plural": "Строки намерения оплаты",
            },
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="unique_intent_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintentitem",
            constraint=models.UniqueConstraint(
                fields=("intent", "charge"), name="unique_charge_per_intent"
            ),
        ),
    ]
