# Generated by Django 5.1.4 on 2026-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentintent_paymentintentitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="secret2_encrypted",
            field=models.TextField(
                blank=True, verbose_name="Дополнительный ключ (шифрованный)"
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="kind",
            field=models.CharField(
                choices=[
                    ("yookassa", "ЮKassa"),
                    ("tbank", "Т-Банк Эквайринг"),
                    ("robokassa", "Робокасса"),
                    ("cloudpayments", "CloudPayments"),
                    ("sbp", "СБП напрямую через банк"),
                    ("manual", "Вручную (без онлайн-оплаты)"),
                ],
                max_length=20,
                verbose_name="Провайдер",
            ),
        ),
    ]
