# Generated by Django 5.1.4 on 2026-09-14 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("payments", "0003_paymentprovider_secret2_encrypted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObligatoryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Назначение")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tax", "Налог"),
                            ("insurance", "Страховые взносы"),
                            ("utility", "Коммунальные услуги"),
                            ("service", "Услуги подрядчиков"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        help_text="ИФНС, поставщик, подрядчик.",
                        max_length=255,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Срок оплаты")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("paid", "Оплачен"),
                            ("canceled", "Отменён"),
                        ],
                        default="planned",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата оплаты"),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Оплачено",
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Внешний ID платежа"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Квитанция, платёжное поручение, требование.",
                        null=True,
                        upload_to="obligatory/",
                        verbose_name="Документ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_obligations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Провёл",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если платёж проводился онлайн.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obligatory_payments",
                        to="payments.paymentprovider",
                        verbose_name="Через провайдера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обязательный платёж",
                "verbose_name_plural": "Обязательные платежи",
                "ordering": ["status", "due_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "due_date"],
                        name="payments_ob_organiz_f7f827_idx",
                    )
                ],
            },
        ),
    ]
