# Generated by Django 5.1.4 on 2026-09-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "joined_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата вступления"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Действующий"),
                            ("inactive", "Выбывший"),
                            ("heir", "Наследник"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Член СНТ",
                "verbose_name_plural": "Члены СНТ",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер участка"),
                ),
                (
                    "area_sotok",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Площадь (соток)",
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Кадастровый номер"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
                "ordering": ["number"],
                "unique_together": {("organization", "number")},
            },
        ),
        migrations.CreateModel(
            name="PlotOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField(verbose_name="Дата начала")),
                (
                    "date_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Основание")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="members.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="members.plot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Владение участком",
                "verbose_name_plural": "История владений",
                "ordering": ["-date_from"],
            },
        ),
    ]
