# Generated by Django 5.1.4 on 2026-09-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                (
                    "price_per_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Тариф (руб./кВт·ч)",
                    ),
                ),
                (
                    "price_per_kwh_night",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Ночной тариф (руб./кВт·ч)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф на электроэнергию",
                "verbose_name_plural": "Тарифы на электроэнергию",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Серийный номер"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Общий счётчик на вводе СНТ.",
                        verbose_name="Главный ввод",
                    ),
                ),
                (
                    "installed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата установки"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — для главного ввода СНТ.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="members.plot",
                        verbose_name="Участок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счётчик",
                "verbose_name_plural": "Счётчики",
                "ordering": ["plot__number"],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Дата снятия")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Показание (день/общее), кВт·ч",
                    ),
                ),
                (
                    "value_night",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Показание (ночь), кВт·ч",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="meter_photos/",
                        verbose_name="Фото показания",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="electricity.meter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Показание счётчика",
                "verbose_name_plural": "Показания счётчиков",
                "ordering": ["-date"],
                "unique_together": {("meter", "date")},
            },
        ),
    ]
