# Generated by Django 5.1.4 on 2026-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreading",
            name="is_estimated",
            field=models.BooleanField(
                default=False,
                help_text="Показание не снято, а рассчитано по среднему: человек не сдал его за период. Нужно, чтобы следующий расчёт отталкивался от уже начисленного, и когда настоящее показание наконец придёт, разница не легла в счёт второй раз.",
                verbose_name="Расчётное",
            ),
        ),
    ]
