# Generated by Django 5.1.4 on 2026-10-06 05:34

from django.db import migrations, models


def move_photos(apps, schema_editor):
    """
    Уже загруженные фото — из открытой meter_photos/ в private/meter_photos/.
    Файл копируется под новым именем, старый удаляется только после
    успешной записи; пропавший файл не валит миграцию — путь остаётся как
    был, и это видно в выводе.
    """
    from django.core.files.storage import default_storage

    MeterReading = apps.get_model("electricity", "MeterReading")
    moved = missing = 0
    for r in MeterReading.objects.exclude(photo="").exclude(photo__isnull=True) \
            .exclude(photo__startswith="private/"):
        old = r.photo.name
        if not default_storage.exists(old):
            missing += 1
            continue
        with default_storage.open(old, "rb") as fh:
            new = default_storage.save("private/" + old, fh)
        r.photo.name = new
        r.save(update_fields=["photo"])
        default_storage.delete(old)
        moved += 1
    if moved or missing:
        print(f"\n  фото показаний: перенесено {moved}, не найдено файлов {missing}")


class Migration(migrations.Migration):

    dependencies = [
        ("electricity", "0002_meterreading_is_estimated"),
    ]

    operations = [
        migrations.RunPython(move_photos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="meterreading",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Лежит в закрытой части хранилища: на фото бывает адрес и лицо; отдаётся только через API с проверкой прав.",
                null=True,
                upload_to="private/meter_photos/",
                verbose_name="Фото показания",
            ),
        ),
    ]
