# Generated by Django 5.1.4 on 2026-09-21 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=150, verbose_name="Логин"),
                ),
                (
                    "resource",
                    models.CharField(max_length=50, verbose_name="Что смотрели"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("list", "Просмотр списка"),
                            ("detail", "Просмотр записи"),
                            ("export", "Выгрузка файла"),
                        ],
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Идентификатор записи"
                    ),
                ),
                (
                    "records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Записей отдано"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=255, verbose_name="Запрос"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="organizations.organization",
                        verbose_name="СНТ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение к персональным данным",
                "verbose_name_plural": "Журнал обращений к персональным данным",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource", "-created_at"],
                        name="core_access_resourc_15ad1c_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_access_user_id_89b778_idx",
                    ),
                ],
            },
        ),
    ]
